### PR TITLE
Fix Makefile and bin/generate

### PR DESCRIPTION
**Pull request by Rainij**
Fix of Errors which made `Makefile` and `bin/generate` unusable.

Some errors are just syntax errors, others are due to the fact that the companion-repo `exercism/problem-specifications` evolved without the above mentioned files being updated.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@exercism/reviewers Anyone know SML to review this?

**Review by kotp — APPROVED** [review]
The changes achieve the intended goals.

Tested locally, it reveals that the `binary` tests are currently problematic.  But the Makefile does what it is supposed to do, verified.

I am using _Poly/ML 5.7.1 Release_.

**Comment by kotp** [comment]
I have also tested `bin/generate`.  The generator has the bad habit of not appending an EOL at the end of what should be the last line, though.  But it now works.  I tested the generator on _Binary_ exercise, which has been deprecated upstream, I did not peek to see if it is deprecated here.

So as far as the intention for this PR, it is effective.

**Comment by Rainij** [comment]
Thank you @kotp for your review and for trying out. My fix is intentionally minimalistic. I also had the impression that more could be done to improve the scripts but I didn't want to change the behavior without knowing what others think is best. I may have time to do some further work in the future. I will have a look into the issues. Maybe there are also some other places where improvements are discussed?

**Comment by kotp** [comment]
> My fix is intentionally minimalistic.

Yeah, I like the focus on this.  I created an issue regarding the requirement to be connected for generating tests.

If you would like, it would be good to have issues created for the other things you noticed as well.  That documents work to be done, and the PR that attends to those can be linked and worked on independently, perhaps some one will get to them before you can.  But that will not happen if they are not at least documented as an issue.

Bringing this in as is.

**Pull request merged**
