### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

Note that we're aiming for 10 lines and a max-width of 40 columns.
This solution has a max-width of 49, so we may want to adjust it.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by mcmillhj** [comment]
If 40 characters is a hard limit, the right-hand side of the second pattern match can be wrapped onto a newline like this: 

```
fun accumulate  _ []     = []
  | accumulate f (x::xs) = 
     f x :: accumulate f xs
```

but the current styling seems canonical within the SML community

**Comment by kytrinyx** [comment]
In that case lets leave it as is and see what it looks like. We can always change it later.

**Comment by snahor** [comment]
Hmm, I think it would be better if we just use the plain ol' fibonacci (inefficient) implementation.

```sml
fun fib 0 = 0
  | fib 1 = 1
  | fib n = fib (n - 1) + fib (n - 2)
```

**Comment by kytrinyx** [comment]
@snahor I like that. It's a lot more classic than this kind of arbitrary "first solution" (since we don't have Hello World here).

**Comment by kytrinyx** [comment]
I've updated to use the fibonacci one.

**Pull request merged**
