### PR TITLE
Remove negation

### PR DESCRIPTION
**Pull request by Munksgaard**
I believe the wording doesn't make sense with this negation.

### CODE REVIEW

**Comment by Munksgaard** [comment]
Actually, looking at the tests, I think I'm supposed to return `NONE` if the input is less than one?

**Comment by rainij** [comment]
@Munksgaard I agree to your observations: the wording should be corrected as you suggested and moreover the comment about raising `Domain` is not consistent with what the tests do. Probably it is easiest to just adjust the description to match the tests.

Maybe you can adjust the wording one more time and then ask one of the maintainers (I am not one of them)? See the other PRs for whom to ping.

**Comment by Munksgaard** [comment]
Good idea @rainij. I have added an additional commit to suggest using `NONE` instead of raising an exception on invalid input.

@ErikSchierboom, I see you've approved some other PRs, would you care to take a look at this one, or point me in the direction of the person who can?

**Review by kotp — APPROVED** [review]
Looks good to me.  I like the change as well to not be "not less than 1" as that negation is another layer of translation.

**Comment by rainij** [comment]
@kotp @ErikSchierboom this PR could probably merged too.

**Comment by ErikSchierboom** [comment]
Done 🎉

**Pull request merged**
