### PR TITLE
Add k4rtik as maintainer

### PR DESCRIPTION
**Pull request by sshine**

### CODE REVIEW

**Comment by sshine** [comment]
@ihid: It seems that "Create a merge commit" is still unavailable on both Haskell and SML tracks.

Do you think it is realistic that we'll get all three merging options back on all tracks except the tracks that have explicitly asked not to have certain merging options available?

**Comment by iHiD** [comment]
@sshine All the right options are checked on both Haskell and SML. You don't see the button?

Screenshot 2020-04-20 at 01 05 48
Screenshot 2020-04-20 at 01 05 58

**Comment by sshine** [comment]
Using the test commit of #133, I do see the button, but the first option when clicking it has "Not enabled for this branch." next to "Create a merge commit", as witnessed in the screenshot below.

I've shown a similar screenshot the last time Katrina tried to fix this.

I suspect that maybe there is an organizational setting that beats the repo setting?

Screenshot 2020-04-20 at 11 38 53

**Comment by iHiD** [comment]
Hmmm. I can do merge commits fine on other repos. Do you have it disabled on your fork maybe?

**Pull request merged**
