### PR TITLE
:wrench: Configure online editor.

### PR DESCRIPTION
**Pull request by BramVanPevenage**
associated issue #142 

used [style guide](https://www.cs.cornell.edu/courses/cs312/2001SP/style.html)

modified indentation to 2

### CODE REVIEW

**Review by rainij — APPROVED** [review]
I looked into the history of `config.json`. The previous value (`4`) seems to be randomly set. So if the style guide you mentioned suggests `2` I am fine with that.

**Comment by rainij** [comment]
@BramVanPevenage sorry for the late feedback, for some reason I got no notification. I just happened to get a notification by another PR.

**Comment by BramVanPevenage** [comment]
@rainij no problem, it will automatically merge after the required statuses and checks are done.

**Comment by rainij** [comment]
@BramVanPevenage maybe you can rebase this to trigger a new run of the configlet CI. Would be nice to merge this.

**Comment by BramVanPevenage** [comment]
check #243

**Pull request closed without merging**
