### PR TITLE
Implements proposal by @snahor in #32 to make xsml track more consistent

### PR DESCRIPTION
**Pull request by mcmillhj**
Implements proposal by @snahor in #32 to make xsml track more consistent

Summary of changes:

1. All test files have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL
2. All stub files now have type signatures to give the user hints about the expect input and output of each function
3. The SETUP.md file has been updated to reflect the new testing methodology

### CODE REVIEW

**Comment by kytrinyx** [comment]
@mcmillhj @snahor I am so sorry for missing this! I had surgery in late February, and a lot of things have fallen through the cracks in the months since then.

Would the two of you be interested in having commit on this track? It looks like you've both contributed a fair amount. I would now be around to help get the conflicts sorted out.

**Comment by kytrinyx** [comment]
By the way—maintaining the track wouldn't necessarily mean doing more than you're already doing, it would mostly mean that between the two of you you can accept the changes into master!

I have some docs about maintaining tracks here: https://github.com/exercism/docs/blob/master/maintaining-a-track/README.md

**Comment by mcmillhj** [comment]
No worries. I certainly won't claim to be an SML expert since I mainly play around in it for fun. I would be happy to manage this track though.

**Comment by kytrinyx** [comment]
Thanks @mcmillhj! You're far more of an expert than I am, though admittedly the bar there is low :) 🌻

**Comment by snahor** [comment]
Could you split it in smaller PRs? it would be easier to review.

**Comment by mcmillhj** [comment]
Yeah, I can do that. Probably wont be able to do so today, but in the next day or so I should have it up.

**Comment by mcmillhj** [comment]
Closing this PR, going submit separate PRs for the accumulate, allergies, anagram, binary, flatten-array, hamming, nth-prime, and raindrop exercises.

**Pull request closed without merging**
