### PR TITLE
Add binary-search exercise

### PR DESCRIPTION
**Pull request by keiravillekode**

### CODE REVIEW

**Review by glennj — APPROVED** [review]

**Comment by glennj** [comment]
I guess my approval doesn't count.

@keiravillekode Should I get added to the team?

**Comment by keiravillekode** [comment]
> @keiravillekode Should I get added to the team?

Yes please.

**Comment by glennj** [comment]
@iHiD or @ErikSchierboom, could I be added to the exercism/sml team please.

**Comment by ErikSchierboom** [comment]
Done

**Pull request merged**
