### PR TITLE
Update example.sml relative path

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Comment by rainij** [comment]
Looks correct to me, but to be honest it is a long time ago when I looked into how the config.json works or what exactly it is responsible for. Can you provide some explanation how this came to your attention? Was something broken? When I did some PRs in this repo (a while ago) I didn't notice this.

Alternatively you could just ask somebody else to review this.

**Comment by BNAndras** [comment]
https://github.com/exercism/sml/actions/runs/6564423719/job/17830751975

`configlet lint` complains if an exercise's example.sml is not in the expected relative location referenced in the files array in the track's config. This must have been a recent change in the last few months since https://github.com/exercism/sml/actions/runs/5554101355 also failed recently but PRs back in April were fine. I suspect before this change, configlet assumed the example.sml was in .meta so you were providing the file's location relative to .meta. In that case, it's probably now looking for example.sml relative to the exercise slug folder which is why we need to prefix the .meta folder path.

**Review by rainij — APPROVED** [review]
@BNAndras thanks for your explanations. I understand now.

Can you merge it, or should I do it?

**Comment by BNAndras** [comment]
I don’t have write access to this repo unfortunately.

**Pull request merged**
