### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by rainij**
The `README.md` is heavily outdated, I essentially rewrote it.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Let me know when you want me to review it.

**Comment by rainij** [comment]
I recently added some exercises and it took me some time to find out what to do. The main reasons are that the current sml-README is outdated and that the exercism wide documentation is rather verbose. Therefore I added a comprehensive section on this topic with concrete steps to follow.

To generate the "boilerplate" when adding an exercise I used the following three commands (after modifying the repo-level `config.json`), which I added to the README:

```shell
$ bin/configlet sync --update --tests include -e {{ slug }} # 1. Add tests.toml including all available tests.
$ bin/configlet sync --update -e {{ slug }}  # 2. Interactively add required files with "generic" content.
$ bin/generate {{ slug }}                    # 3. Autogenerate required files with sml-specific content.
```

I would have liked it to execute `configlet` only once and without any interactive prompts since I suppose `yes` is right most of the time. But for me there were two inconveniences (just my personal opinion):

1. `--yes` never works if `--tests` is explicitly specified, not even with `--tests include` where `configlet` still complains about the mode `choose`. Example:

```shell
$ bin/configlet sync --update --docs --filepaths --metadata --tests include --yes -e beer-song
Error: '-y, --yes' was provided to non-interactively update, but the tests updating mode is still 'choose'.
...
```
Don't know if this is a bug?

2. To avoid interactivity in step 2 one can use `--yes` but only if one specifies `--docs --filepaths --metadata` too. Note that I actually only want to exclude `--tests` because of incompatibility with `--yes`. Hence I do not like to give all these options explicitly because I feel this to be a little more brittle against future changes on the tool.

**@ErikSchierboom  So in case I do something wrong just correct me and I will change the part in the README accordingly.**

**Comment by ErikSchierboom** [comment]
> Don't know if this is a bug?

I'll look into it, but it is definitely not ideal (CC @ee7) I've ran into this myself too. I've opened an issue: https://github.com/exercism/configlet/issues/673

**Comment by rainij** [comment]
Thanks @ee7  for the explanations and rationale behind `confglet`. Might be true that it is less brittle then I think.

I suppose that if a new kind of files will be added then probably `configlet lint` would check if they are present (in case they are required).

So it is *just* a little bit inconvenient to specify all these options. But this is probably acceptable and one might even argue that it is good to think about what one really wants :smile: .

I would also be against a *separate* `--test-mode` option, even if it solves my second issue somehow I would not like it since it looks more complicated in some sense.

Just in case somebody still considers to reduce the verbosity. My first impulse was that something like this would have been nice:
- *explicitly* stating that one wants everything (`--all`) by `configlet sync -u --all` and *not* implicitly by `configlet sync -u`,
- overwrite the defaults like so `configlet sync -u --all --tests include -y`,
- dealing with the boolean options by allowing an optional arg like so `configlet sync -u --all --tests include --docs no -y` (or alternatively `--no-docs`).

But as said, this is just a "first impulse". I did not carefully think about it and I am hence I don't know if it was a good idea. *And*: I definitely don't want to produce needless work for you - just a random thought for you information :smile: .

I think fixing https://github.com/exercism/configlet/issues/673 is really sufficient for now. If it is quickly merged I might even change the README accordingly within this PR.

**Comment by rainij** [comment]
@ee7 the new release of `configlet` works fine, I am able to run the formerly forbidden combination of options. I updated the README of this repo accordingly.

**Comment by rainij** [comment]
@ErikSchierboom updated the README in response to the already mentioned bugfix. This MR can now be reviewed (but it is not urgent of course).

**Review by ErikSchierboom — APPROVED** [review]
Note that there is still a bug that could bite you: https://github.com/exercism/configlet/issues/297

**Pull request merged**
