### PR TITLE
Sync two-fer docs with problem-specifications

### PR DESCRIPTION
**Pull request by kytrinyx**
The two-fer exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.

For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:

- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2204

### CODE REVIEW

**Review by rainij — APPROVED** [review]
This `two-fer` exercise always irritated me a bit. Especially the introduction is much better now.

**Comment by rainij** [comment]
@kytrinyx in case you expect me to merge this just let me know. There seems to be no consistent protocol in this repo. I usually assume that the person which opened the request merges it upon approval.

**Comment by kytrinyx** [comment]
@rainij Thanks for asking! Yeah, the lack of protocol is adds a bit of ambiguity across the board on Exercism. I'll think about how to improve the wording on the PRs to help clarify that.

I'd definitely appreciate it if you merge these as you see fit.
If not I'm planning on auto-merging any approved PRs after 7 days.

**Comment by rainij** [comment]
> I'll think about how to improve the wording on the PRs to help clarify that.

@kytrinyx this sounds great. I will merge the two PRs on this track.

**Pull request merged**
